name: interference
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - numpy
  - scipy
  - scikit-learn
  - pandas
  - matplotlib
  - prettytable
  - pip
  - pip:
      - torch
      - pymatgen
      - matminer
      - mp-api          # optional: only needed for download_mp_current.py
