"""
figure_angular_signal.py
------------------------
Angular gradient signal strength in (‖r‖, θ) space.

Shows that iiLoss maintains full angular steering throughout training,
while EdLoss loses angular steering power as ‖r‖ → 0 (the fading signal
problem: EdLoss angular gradient ∝ ‖r‖² → 0 as the model improves).

Dummy trajectories are generated by Euler integration of the gradient ODEs,
normalised so both models start with the same initial angular rate.
"""

import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.colors import Normalize

plt.rcParams.update({'font.family': 'sans-serif', 'font.size': 11,
                     'axes.linewidth': 0.8})

# ── Grid in (‖r‖, θ) space ───────────────────────────────────────────────────
R_MAX   = 1.8
r_vals  = np.linspace(0.0, R_MAX, 400)
th_vals = np.linspace(0.0, np.pi / 2, 400)
R, TH   = np.meshgrid(r_vals, th_vals)

# ── Reference point: start of training ───────────────────────────────────────
r0  = 1.5
th0 = np.pi / 3   # 60°

# ── Angular gradient signals ─────────────────────────────────────────────────
# iiLoss: |∂ξ²/∂θ| = 2|sin 2θ|   — independent of ‖r‖
ii_ref = 2 * np.abs(np.sin(2 * th0))
sig_ii = 2 * np.abs(np.sin(2 * TH)) / ii_ref   # normalised to 1 at start

# EdLoss: |∂Ed²/∂θ| ∝ ‖r‖² · |sin 2θ|   — fades quadratically
ed_ref = r0**2 * 2 * np.abs(np.sin(2 * th0))
sig_ed = R**2 * 2 * np.abs(np.sin(2 * TH)) / ed_ref   # also = 1 at start

VMAX = sig_ii.max() * 1.02   # shared colour scale

# ── Dummy training trajectories (Euler ODE integration) ──────────────────────
# Both models:   dr/dt  = -a·r                 (MSE radial decay)
# iiLoss:        dθ/dt  = +b · sin(2θ)         (constant angular rate)
# EdLoss:        dθ/dt  = +b/r0² · r² · sin(2θ) (same initial rate, fades as r²)
dt   = 0.012
n    = 500
a    = 1.1     # common decay rate
b    = 0.65    # iiLoss angular rate


def simulate(angular_rate_fn, r0=r0, th0=th0):
    rs, ths = [r0], [th0]
    r, th = r0, th0
    for _ in range(n):
        r  = max(r  - a * r * dt, 1e-4)
        th = min(th + angular_rate_fn(r) * np.sin(2 * th) * dt,
                 np.pi / 2 - 0.008)
        rs.append(r)
        ths.append(th)
    return np.array(rs), np.array(ths)


r_ii, th_ii = simulate(lambda r: b)                   # constant
r_ed, th_ed = simulate(lambda r: (b / r0**2) * r**2)  # fades with r²

# ── Figure ────────────────────────────────────────────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(12, 5.2))
fig.subplots_adjust(left=0.08, right=0.88, wspace=0.32)

norm_c = Normalize(vmin=0, vmax=VMAX)
CMAP   = 'plasma'

panel_info = [
    ('a)', r'iiLoss  —  $|\partial\mathcal{L}_{\xi^2}/\partial\theta| \propto |\sin 2\theta|$',
     sig_ii, r_ii, th_ii),
    ('b)', r'EdLoss  —  $|\partial\mathcal{L}_\mathrm{Ed}/\partial\theta| \propto \|\mathbf{r}\|^2|\sin 2\theta|$',
     sig_ed, r_ed, th_ed),
]

for ax, (panel_lbl, title, sig, r_t, th_t) in zip(axes, panel_info):

    # ── Background heatmap (x inverted: large ‖r‖ left = early training) ────
    ax.pcolormesh(r_vals, np.degrees(th_vals), sig,
                  cmap=CMAP, norm=norm_c, rasterized=True)

    # ── θ = 90° target line ──────────────────────────────────────────────────
    ax.axhline(90, color='white', lw=1.0, ls='--', alpha=0.45)
    ax.text(R_MAX * 0.97, 88.2, r'$\theta=90°$  ($\xi = 0$)',
            color='white', fontsize=8.5, ha='right', alpha=0.70)

    # ── Training trajectory ──────────────────────────────────────────────────
    ax.plot(r_t, np.degrees(th_t), color='white', lw=2.3, alpha=0.92)

    # Start / end markers
    ax.plot(r_t[0],  np.degrees(th_t[0]),  'o', color='white',
            ms=9, zorder=6, label='Start')
    ax.plot(r_t[-1], np.degrees(th_t[-1]), '*', color='white',
            ms=13, zorder=6, label='End')

    # Direction arrow at midpoint (points toward smaller ‖r‖ = right)
    mid = len(r_t) // 2
    ax.annotate('',
                xy=(r_t[mid + 10], np.degrees(th_t[mid + 10])),
                xytext=(r_t[mid - 10], np.degrees(th_t[mid - 10])),
                arrowprops=dict(arrowstyle='->', color='white', lw=2.0))

    # ── Annotations ──────────────────────────────────────────────────────────
    # Training direction label
    ax.text(0.97, 0.04, r'training progresses $\rightarrow$',
            transform=ax.transAxes, fontsize=8.5,
            color='white', alpha=0.72, ha='right', va='bottom')

    # Panel label
    ax.text(-0.13, 1.04, panel_lbl, transform=ax.transAxes,
            fontsize=19, fontweight='bold', va='bottom')
    ax.set_title(title, fontsize=11, pad=7)

    # ── Axes ─────────────────────────────────────────────────────────────────
    ax.set_xlim(R_MAX, 0)   # inverted: early training (large ‖r‖) on left
    ax.set_ylim(0, 90)
    ax.set_xlabel(r'Residual norm $\|\mathbf{r}\|$  (large = early training)',
                  fontsize=11)
    ax.set_ylabel(r'Angle $\theta$ [°]  (90° = perfect cancellation)',
                  fontsize=11)
    ax.tick_params(top=False, right=False)
    ax.legend(loc='lower left', fontsize=8.5, framealpha=0.3,
              facecolor='black', labelcolor='white', edgecolor='none')

# EdLoss-specific: annotate the stagnation zone
final_th_ed = np.degrees(th_ed[-1])
axes[1].annotate(
    f'stagnates at θ ≈ {final_th_ed:.0f}°',
    xy=(r_ed[-1], final_th_ed),
    xytext=(0.55, 0.22),
    textcoords='axes fraction',
    fontsize=9, color='white', alpha=0.9,
    arrowprops=dict(arrowstyle='->', color='white', lw=1.3, alpha=0.8),
)

# Shared colourbar
cbar_ax = fig.add_axes([0.905, 0.15, 0.018, 0.70])
sm = plt.cm.ScalarMappable(cmap=CMAP, norm=norm_c)
sm.set_array([])
cbar = fig.colorbar(sm, cax=cbar_ax)
cbar.set_label(r'Angular steering signal $|\partial\mathcal{L}/\partial\theta|$'
               '\n(normalised to 1 at start)',
               fontsize=9.5)

plt.savefig('figure_angular_signal.png', dpi=150, bbox_inches='tight')
print('Saved → figure_angular_signal.png')
